### ISSUE TITLE
Ease the process to add extra volumes for local data registration

### ISSUE THREAD

**Issue by ClementGautier** [SubstraFoundation/substra-backend#380]
Hi 👋 

I find it cumbersome to attach an external volume to the backend worker and server. The current process requires to copy / paste the volume list in the default values and add yours to the list but it's error prone and make it harder to maintain (at each upgrade I have to be sure that the default list have not been altered). Also using this method you either have to use hostPath or a StorageClass, you can't define the pvc/pv using another provisioner that would require annotations on the pvc for example.

I suggest: 
1) Adding a more flexible `extraVolumes` and `extraVolumeMounts` entry to ease the configuration. This is a fairly common pattern among chart maintainers that help operations: https://hackernoon.com/the-art-of-the-helm-chart-patterns-from-the-official-kubernetes-charts-8a7cafa86d12 (chapter "3 Empowering Our Fellow Chart Developers")
2) Hardcode volumes that are required. The list of volumes in the chart default values isn't really optional at the moment: if I override the `volumes` variable and ommit a volume by mistake the backend won't work. It appears that nobody should ever touch this value so it make sense to me to simplify the values by hardcoding those mandatory volumes. 

I hope the feedback help making the chart a little bit easier to use.

**Comment by AlexandrePicosson** [comment]
Hello @ClementGautier,

Since the release [1.8.0](https://github.com/SubstraFoundation/substra-backend/blob/6ae966cf6a02893c0a70da6adb86e66954200d1f/charts/substra-backend/CHANGELOG.md#180) of the substra-backend chart it is not necessary anymore to copy the whole `persistence.volumes` object.
For example if in your values you define only something like this:

```yaml
persistence:
  volumes:
    customVolume:
      size: "2Gi"
      readOnly:
        server: false
        worker: true
```

you will have a new volume mounted on your backend and worker pod under the `/var/substra/medias/` path.
Result in the rendered yaml:

```yaml
containers:
      - name: substra-backend        
        volumeMounts:
          - name: data-customVolume
            mountPath: /var/substra/medias/customVolume
            readOnly: false
```

tied to the following pvc:

```yaml
      - name: data-customVolume
        persistentVolumeClaim:
          claimName: RELEASE-NAME-substra-backend-customVolume
```

but all the required pvc's (`compositealgos`, `computeplan`, ...) will still be present alongside this new one.

For the point number two they are not hardcoded to be able to specify volume sizes independently which can be useful sometimes, but as stated above you do not need to redefine the wole list of volumes anymore. This it a benefit from the transition we made from a yaml list to a yaml object.
